Repository llBackend7/MOIZA, pull requests merged in 2023-06, with the labels that each got.

#20 Fix: 모임 추천 리스트 - 그룹원들이 선택한 시간 중에서, 모임 시간동인 겹치는 시간대 조회
  src/main/java/com/ll/MOIZA/boundedContext/selectedTime/service/SelectedTimeService.java
  src/test/java/com/ll/MOIZA/boundedContext/selectedTime/service/SelectedTimeServiceQueryTest.java
Labels: bug, enhancement

#21 fix: 테스트용 initData 수정
  src/main/java/com/ll/MOIZA/base/initData/NotProd.java
Labels: bug

#23 Feat: 모임생성 페이지(메인페이지) 추가
  src/main/java/com/ll/MOIZA/base/security/SecurityConfig.java
  src/main/java/com/ll/MOIZA/boundedContext/home/controller/HomeController.java
  src/main/java/com/ll/MOIZA/boundedContext/member/service/MemberService.java
  src/main/resources/templates/home/main.html
  src/test/java/com/ll/MOIZA/boundedContext/selectedTime/service/SelectedTimeServiceQueryTest.java
Labels: enhancement
